<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

#Reference:

https://www.geeksforgeeks.org/take-matrix-input-from-user-in-python/

https://www.tutorialspoint.com/How-to-Multiply-Two-Matrices-using-Python

In [60]:
def matrix_mul(A, B):
    C=[]  
    R1=len(A)
    R2=len(B)
    C1=len(A[0])
    C2=len(B[0])
    print('Size oF Matrix-A:' ,R1,C1, 'Size oF Matrix-B:' ,R2,C2)
    if C1 == R2:
       for i in range(R1):
           c=[]
           for j in range(C2):  
               num=0
               for k in range(R2):          
                   num = num+A[i][k]*B[k][j]    
               c.append(num)
           C.append(c)   
       for i in range(R1):    
          for j in range(C2):
              print(C[i][j], end = " ")      
          print()
       return(C)        
    else:
       return(print("enter proper matrices to be multiplied"))

R1=int(input("Enter the Number of Rows for the Matrix-A:"))
C1=int(input("Enter the Number of Columns for the Matrix-A:"))

A=[]
print("Enter the entries/numbers ROW-WISE :")
for i in range(R1):
    a=[]
    for j in range(C1):
        a.append(int(input()))      
    A.append(a)   
for i in range(R1):    
    for j in range(C1):
        print(A[i][j], end = " ")      
    print()   
    
    
R2=int(input("Enter the Number of Rows for the Matrix-B:"))
C2=int(input("Enter the Number of Columns for the Matrix-B:"))

B=[]
print("Enter the entries/numbers ROW-WISE :")
for i in range(R2):
    b=[]
    for j in range(C2):
        b.append(int(input()))      
    B.append(b)   
for i in range(R2):    
    for j in range(C2):
        print(B[i][j], end = " ")      
    print()  
matrix_mul(A, B)  



Enter the Number of Rows for the Matrix-A:2
Enter the Number of Columns for the Matrix-A:2
Enter the entries/numbers ROW-WISE :
2
3
5
6
2 3 
5 6 
Enter the Number of Rows for the Matrix-B:2
Enter the Number of Columns for the Matrix-B:1
Enter the entries/numbers ROW-WISE :
6
4
6 
4 
Size oF Matrix-A: 2 2 Size oF Matrix-B: 2 1
24 
54 


[[24], [54]]

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [64]:
import random
def pick_a_number_from_list(A):
    p=random.uniform(min(A),max(A)) 
    print('Random number selected through uniform function:', p)
    min_diff=max(A)
    for i in range(len(A)):
        diff=abs(A[i]-p)
        if diff < min_diff:
            min_diff=diff
            Selected_Num=A[i]
        else:
            continue
    return Selected_Num

A = [0,5, 27, 6, 13, 28, 100, 45, 10, 79]
def sampling_based_on_magnitued():
    for i in range(1,2):
        number = pick_a_number_from_list(A)
        print('Number Selected from the given list:',number)
sampling_based_on_magnitued()

Random number selected through uniform function: 26.41218328833159
Number Selected from the given list: 27


<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [65]:
import re
String='#2a$#b%c%561#'
def replace_digits(String):
    String = re.sub("[^0-9]+",'',String)
    String = re.sub("\d",'#',String) 

    return(String) 

replace_digits(String)

'####'

<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [66]:
def display_dash_board(students, marks):
    #creating Dictionary
    student_records={}
    for i in range(len(Students)):
        student_records[Marks[i]]=Students[i]
    #TOP5
    print("Top 5 Students:")
    top5=sorted (student_records.keys(),reverse=True)[:5]  #sorting in ascending Order  
    for i in range(5):
        print(student_records[top5[i]],top5[i])#printing the top 5
    #Least5
    print("least 5 Students:")
    least5=sorted (student_records.keys())[:5]#sorting in descending Order  
    for i in range(5):    
        print(student_records[least5[i]],least5[i])  #printing the least 5
    #25-75
    st_list=sorted(student_records.keys())
    print("Students whogot marks between >25th percentile <75th percentile:")
    for i in range(len(st_list)):
        if st_list[i]>25 and st_list[i]<75:
            print(student_records[st_list[i]],st_list[i])
        else:
            continue
    return 


Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
display_dash_board(Students, Marks)


Top 5 Students:
student8 98
student10 80
student2 78
student5 48
student7 47
least 5 Students:
student3 12
student4 14
student9 35
student6 43
student1 45
Students whogot marks between >25th percentile <75th percentile:
student9 35
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [67]:
import math
S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

p=P[0]   #Assigning point P values to p & q
q=P[1]
dist_records={}
def closest_points_to_p(S, P):
    for i in range(len(S)):
        x=S[i][0]
        y=S[i][1]
        num=((x*p)+(y*q))       
        den1=math.sqrt(x*x +y*y)
        den2=math.sqrt((p*p)+(q*q))
        den=den1*den2
        value=math.acos(num/den)
        dist_records[value]=S[i] #dictionary for point and its cosine dist from point P
    closest5=sorted (dist_records.keys())[:5] #Sorting Least % distance   
    for i in range(5):
        print(dist_records[closest5[i]],closest5[i])
    return closest_points_to_p
points = closest_points_to_p(S, P)
print()

(6, -7) 0.06512516333438509
(1, -1) 0.14189705460416438
(6, 0) 0.9272952180016123
(-5, -8) 1.2021004241368467
(-1, -1) 1.4288992721907328



<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [108]:
import math

def i_am_the_one(red,blue,line):
    print('for line :',line)
    cf_list=[]
    for i in range(len(line)):
        cf_list.append(line[i])
    print(cf_list)
    cf_x=int(cf_list[0])
    cf_y_sign=cf_list[2]
    cf_y=int(cf_list[3])
    cf_c=int(cf_list[6])
    cf_x=int(cf_list[0])
    cf_c_sign=cf_list[5]
    print(cf_c_sign)
    sign=''
    sign_pt=''
    count=0
    for j in red:
        print(j)
        if count==0:
            count=count+1
            print('in j=0')
            print(cf_c_sign)
            if cf_y_sign=='+':
                
                value=(cf_x*j[0])+(cf_y*j[1])
            else:
                value=(cf_x*j[0])-(cf_y*j[1])  
            if cf_c_sign=='-':
                value=value-cf_c
            else:
                value-value+cf_c                
            print(value)
            if value > 0:
                sign='positive'
            elif value < 0:
                sign='negative'  
            else:
                print('on the line')
                return 0
            print(sign)
            continue
        else:
            print(cf_c_sign)
            if cf_y_sign=='+':    
                value=(cf_x*j[0])+(cf_y*j[1])
            else:
                value=(cf_x*j[0])-(cf_y*j[1])  
            if cf_c_sign=='-':
                value=value-cf_c
            else:
                value-value+cf_c                
            print(value)
            print(value)
            if value > 0:
                sign_pt='positive'
            elif value < 0:
                sign_pt='negative'  
            else:
                print('on the line')
                return 0
            if sign_pt==sign:
                print('similar')
            else:
                print('different')
                return 0
            
    return #yes/no

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print() # the returned value

for line : 1x+1y+0
['1', 'x', '+', '1', 'y', '+', '0']
+
(1, 1)
in j=0
+
2
positive
(2, 1)
+
3
3
similar
(4, 2)
+
6
6
similar
(2, 4)
+
6
6
similar
(-1, 4)
+
3
3
similar

for line : 1x-1y+0
['1', 'x', '-', '1', 'y', '+', '0']
+
(1, 1)
in j=0
+
0
on the line

for line : 1x+0y-3
['1', 'x', '+', '0', 'y', '-', '3']
-
(1, 1)
in j=0
-
-2
negative
(2, 1)
-
-1
-1
similar
(4, 2)
-
1
1
different

for line : 0x+1y-0.5
['0', 'x', '+', '1', 'y', '-', '0', '.', '5']
-
(1, 1)
in j=0
-
1
positive
(2, 1)
-
1
1
similar
(4, 2)
-
2
2
similar
(2, 4)
-
4
4
similar
(-1, 4)
-
4
4
similar



In [82]:
word = '1x+2y+9'
alpha=[]
for i in range(len(word)):
    alpha.append(word[i])
alpha

['1', 'x', '+', '2', 'y', '+', '9']

<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [65]:

def curve_smoothing(str):
    #print(str)
    for i in range(len(str)):
        #print('i is',i)
        if str[i]=='_' and i==0:
            count=2
            for j in range(len(str)-1):
                j=j+1
                if str[j]=='_':
                    count=count+1
                else:
                    value=(int(str[j])/count)
                    for k in range(j):
                        str[k]=value
                    str[k+1]=value 
                    print('1st:',str)
                    break

        elif str[i]=='_' and i!=0:
            count=2
            value=str[i-1]
            for j in range(len(str)-1-i):
                j=i+1+j
                if str[j]=='_':
                    count=count+1
                elif str[j]!='_':
                    value=value+(str[j])
                    count=count+1
                    value=value/count
                    for k in range(count):
                        str[i+k-1]=value
                    print(str)
                    break 
            if j==(len(str)-1):       
                value=value/count
                for k in range(count):
                    str[i-1+k]=value
                print(str)
    return str

S=  "_,_,30,_,_,_,50,_,_"
str=S.split(',')
for i in range(len(str)):
    if str[i]!='_':
        str[i]=int(str[i])
smoothed_values= curve_smoothing(str)

1st: [10.0, 10.0, 10.0, '_', '_', '_', 50, '_', '_']
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 12.0, '_', '_']
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [3]:
A=['w','f']

In [59]:
def compute_conditional_probabilites(A):
    unique_list_S = []
    unique_list_F = []
    sec_col_S=[]
    col_dict={}
    for i in range(len(A)): 
        sec_col_S.append(A[i][1])
        if A[i][1] not in unique_list_S: 
            unique_list_S.append(A[i][1])
        if A[i][0] not in unique_list_F: 
            unique_list_F.append(A[i][0])
            
    #print(unique_list_F[0])   
    #print(sec_col.count(unique_list[0]))
    for i in range(len(unique_list_S)):
        col_dict[unique_list_S[i]]=sec_col_S.count(unique_list_S[i])
    #print(col_dict)
    #print(col_dict['S1'])
    
    for j in range(len(unique_list_F)):
        print('\n')
        for k in range(len(unique_list_S)):
            prob=[]
            prob.append(unique_list_F[j])
            prob.append(unique_list_S[k])
            #print(prob)
            num=A.count(prob)
            den=col_dict[prob[1]]
            #print(num,den)
            #P(F=F1|S==S1)=1/4
            print('P(F=',unique_list_F[j],'/S=',unique_list_S[k],')=',num/den,end =", ")
    
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
compute_conditional_probabilites(A)



P(F= F1 /S= S1 )= 0.25, P(F= F1 /S= S2 )= 0.3333333333333333, P(F= F1 /S= S3 )= 0.0, 

P(F= F2 /S= S1 )= 0.25, P(F= F2 /S= S2 )= 0.3333333333333333, P(F= F2 /S= S3 )= 0.3333333333333333, 

P(F= F3 /S= S1 )= 0.0, P(F= F3 /S= S2 )= 0.3333333333333333, P(F= F3 /S= S3 )= 0.3333333333333333, 

P(F= F4 /S= S1 )= 0.25, P(F= F4 /S= S2 )= 0.0, P(F= F4 /S= S3 )= 0.3333333333333333, 

P(F= F5 /S= S1 )= 0.25, P(F= F5 /S= S2 )= 0.0, P(F= F5 /S= S3 )= 0.0, 

<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [34]:

def string_features(S1, S2):
    w1=S1.split()
    w2=S2.split()
    a=0
    b=[]
    c=[]
    for i in range(len(W1)):
        if w1[i] in w2:
            a=a+1
        else:
            b.append(w1[i])
        if w2[i] not in w1:
            c.append(w2[i])  
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
a,b,c

(7, ['first', 'F', '5'], ['second', 'S', '3'])

<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [15]:
import math as mt
def compute_log_loss(A):
    cnt=len(A)
    sum1=0
    print(cnt)
    for i in range(len(A)):
        sum1=sum1+(A[i][0]*(mt.log10(A[i][1])))
    loss=sum1/cnt    
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)

8
